// demo/fixtures/adapters-fit.solid.tsx
/** @jsxImportSource solid-js */
import { render } from "solid-js/web";
import { For } from "solid-js";
import { BottomSheet } from "@surdeddd/bottom-sheet/solid";
import type { BottomSheetEngine } from "../../src/core/BottomSheetEngine";
import { POINTS, ROWS, hostFor, type AdapterHandle } from "./adapters-fit-shared";

export const mountSolid = (): AdapterHandle => {
  let engine: BottomSheetEngine | null = null;
  render(
    () => (
      <BottomSheet
        snapPoints={POINTS}
        initial="closed"
        animation="tween"
        lockBodyScroll={false}
        fitContentToSnap
        engineRef={next => {
          engine = next;
        }}
        footer={
          <button type="button" data-action="solid">
            action
          </button>
        }
      >
        <For each={ROWS}>
          {i => (
            <div class="row" data-row={i} data-owner="solid">
              row {i}
            </div>
          )}
        </For>
      </BottomSheet>
    ),
    hostFor("solid"),
  );
  return {
    open: id => engine!.open(id),
    close: () => engine!.close(),
  };
};

// demo/fixtures/adapters-fit-react.tsx
import { createRef } from "react";
import { createRoot } from "react-dom/client";
import {
  BottomSheet,
  type BottomSheetHandle,
} from "@surdeddd/bottom-sheet/react";
import { POINTS, ROWS, hostFor, type AdapterHandle } from "./adapters-fit-shared";

export const mountReact = (): AdapterHandle => {
  const sheet = createRef<BottomSheetHandle>();
  createRoot(hostFor("react")).render(
    <BottomSheet
      ref={sheet}
      snapPoints={POINTS}
      initial="closed"
      animation="tween"
      lockBodyScroll={false}
      fitContentToSnap
      footer={
        <button type="button" data-action="react">
          action
        </button>
      }
    >
      {ROWS.map(i => (
        <div className="row" data-row={i} data-owner="react" key={i}>
          row {i}
        </div>
      ))}
    </BottomSheet>,
  );
  return {
    open: id => sheet.current!.open(id),
    close: () => sheet.current!.close(),
  };
};
