// src/react/BottomSheet.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from "react";
import { useBottomSheet } from "./useBottomSheet";
import type { BottomSheetEngine } from "../core/BottomSheetEngine";
import type { EngineOptions, EngineState } from "../core/types";

const useHasMounted = () => {
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  return mounted;
};

type EngineOptionsForProps = Omit<
  EngineOptions,
  "element" | "handle" | "scrollContainer" | "backdrop" | "scrim"
>;

export type HeaderProp = ReactNode | ((state: EngineState) => ReactNode);

export type BottomSheetProps = EngineOptionsForProps & {
  backdrop?: boolean;
  closeOnBackdrop?: boolean;
  className?: string;
  style?: CSSProperties;
  header?: HeaderProp;
  children?: ReactNode;
  leftButton?: ReactNode;
  rightButton?: ReactNode;
  screen?: ReactNode;
  onChange?: (state: EngineState) => void;
  ariaLabel?: string;
  ariaLabelledBy?: string;
  noSSR?: boolean;
};

export type BottomSheetHandle<TId extends string = string> = {
  snapTo: (id: TId) => Promise<void>;
  open: (id?: TId) => Promise<void>;
  close: () => Promise<void>;
  setAllowed: (ids: TId[], snap?: TId) => void;
  setSnapPoints: (
    points: import("../core/types").EngineOptions["snapPoints"],
    allowed?: string[],
  ) => void;
  setScrim: (opts: import("../core/types").ScrimUpdate) => void;
  setScrimOverlay: (
    opts: import("../core/types").ScrimOverlayOptions,
  ) => () => void;
  state: EngineState & { activeId: TId };
  getEngine: () => BottomSheetEngine | null;
};

export const BottomSheet = forwardRef<BottomSheetHandle, BottomSheetProps>(
  function BottomSheet(props, ref) {
    const {
      backdrop = true,
      closeOnBackdrop = true,
      className = "",
      style,
      header,
      children,
      leftButton,
      rightButton,
      screen,
      onChange,
      ariaLabel = "Bottom sheet",
      ariaLabelledBy,
      noSSR = false,
      ...engineOpts
    } = props;
    const mounted = useHasMounted();

    const {
      sheetRef,
      handleRef,
      contentRef,
      backdropRef,
      screenRef,
      state,
      snapTo,
      open,
      close,
      setAllowed,
      getEngine,
    } = useBottomSheet(engineOpts);

    const isVerticalAxis =
      (engineOpts.mode ?? "bottom") === "bottom" ||
      (engineOpts.mode ?? "bottom") === "top";
    const ariaModal = engineOpts.focusTrap === true;
    const allowedIds =
      engineOpts.allowed ?? engineOpts.snapPoints.map(p => p.id);
    const activeIdx = allowedIds.indexOf(state.activeId);

    const lastAnnouncedRef = useRef<string>("");
    const [announce, setAnnounce] = useState("");
    useEffect(() => {
      if (state.activeId !== lastAnnouncedRef.current) {
        lastAnnouncedRef.current = state.activeId;
        setAnnounce(state.activeId);
      }
    }, [state.activeId]);

    useImperativeHandle(
      ref,
      () => ({
        snapTo,
        open,
        close,
        setAllowed,
        setSnapPoints: (points, allowed) =>
          getEngine()?.setSnapPoints(points, allowed),
        setScrim: opts => getEngine()?.setScrim(opts),
        setScrimOverlay: opts => getEngine()?.setScrimOverlay(opts) ?? (() => {}),
        getEngine,
        get state() {
          return getEngine()?.state ?? state;
        },
      }),
      [snapTo, open, close, setAllowed, getEngine, state],
    );

    useEffect(() => {
      onChange?.(state);
    }, [state, onChange]);

    if (noSSR && !mounted) return null;

    return (
      <div className="bs-root">
        {backdrop && (
          <div
            ref={backdropRef as React.RefObject<HTMLDivElement>}
            className="bs-backdrop"
            onClick={closeOnBackdrop ? () => void close() : undefined}
          />
        )}
        <div
          ref={screenRef as React.RefObject<HTMLDivElement>}
          className="bs-screen"
        >
          {screen}
        </div>
        <section
          ref={sheetRef as React.RefObject<HTMLElement>}
          className={`bs-sheet ${className}`.trim()}
          style={style}
          data-mode={engineOpts.mode ?? "bottom"}
          data-active={state.activeId}
          role={ariaModal ? "dialog" : "region"}
          aria-modal={ariaModal ? "true" : undefined}
          aria-label={ariaLabelledBy ? undefined : ariaLabel}
          aria-labelledby={ariaLabelledBy}
        >
          {leftButton && (
            <div className="bs-button-slot" data-side="left">
              {leftButton}
            </div>
          )}
          {rightButton && (
            <div className="bs-button-slot" data-side="right">
              {rightButton}
            </div>
          )}
          <div
            ref={handleRef as React.RefObject<HTMLDivElement>}
            className="bs-handle"
            role="slider"
            tabIndex={0}
            aria-orientation={isVerticalAxis ? "vertical" : "horizontal"}
            aria-valuemin={0}
            aria-valuemax={Math.max(0, allowedIds.length - 1)}
            aria-valuenow={Math.max(0, activeIdx)}
            aria-valuetext={state.activeId}
            aria-label="Resize sheet"
          >
            {typeof header === "function" ? header(state) : header}
          </div>
          <div
            ref={contentRef as React.RefObject<HTMLDivElement>}
            className="bs-content"
            tabIndex={0}
            role="region"
            aria-label="Sheet content"
          >
            {children}
          </div>
          <span className="bs-sr-only" role="status" aria-live="polite">
            {announce}
          </span>
        </section>
      </div>
    );
  },
);

// src/svelte/BottomSheet.svelte
<script lang="ts" generics="TId extends string = string">
  import { onMount, onDestroy, untrack, type Snippet } from "svelte";
  import { BottomSheetEngine } from "../core/BottomSheetEngine";
  import type {
    EngineState,
    SnapPointDef,
    SheetMode,
    ScrimUpdate,
    ScrimOverlayOptions,
    EngineOptions,
  } from "../core/types";

  type Props = {
    snapPoints: SnapPointDef<TId>[];
    allowed?: TId[];
    initial?: TId;
    mode?: SheetMode;
    animation?: "spring" | "tween";
    spring?: { stiffness?: number; damping?: number; mass?: number };
    focusTrap?: boolean;
    closeOnEscape?: boolean;
    closeOnBack?: boolean;
    lockBodyScroll?: boolean;
    rubberBand?: boolean;
    backdropRange?: [number, number];
    backdrop?: boolean;
    closeOnBackdrop?: boolean;
    ariaLabel?: string;
    header?: Snippet<[EngineState & { activeId: TId }]>;
    leftButton?: Snippet;
    rightButton?: Snippet;
    screen?: Snippet;
    children?: Snippet;
    onsnap?: (id: TId) => void;
    onopen?: (id: TId) => void;
    onclose?: () => void;
    onchange?: (state: EngineState & { activeId: TId }) => void;
  };

  let {
    snapPoints,
    allowed,
    initial,
    mode = "bottom",
    animation = "spring",
    spring,
    focusTrap = false,
    closeOnEscape = true,
    closeOnBack = false,
    lockBodyScroll = true,
    rubberBand = true,
    backdropRange,
    backdrop = true,
    closeOnBackdrop = true,
    ariaLabel = "Bottom sheet",
    header,
    leftButton,
    rightButton,
    screen,
    children,
    onsnap,
    onopen,
    onclose,
    onchange,
  }: Props = $props();

  let sheetEl: HTMLElement | undefined = $state();
  let handleEl: HTMLElement | undefined = $state();
  let contentEl: HTMLElement | undefined = $state();
  let backdropEl: HTMLElement | undefined = $state();
  let screenEl: HTMLElement | undefined = $state();

  let viewState: EngineState & { activeId: TId } = $state({
    size: 0,
    activeId: untrack(
      () => (initial ?? snapPoints[0]?.id ?? "default") as TId,
    ),
    isDragging: false,
    isAnimating: false,
    progress: 0,
  });

  let engine: BottomSheetEngine | null = null;

  onMount(() => {
    if (!sheetEl) return;
    engine = new BottomSheetEngine({
      element: sheetEl,
      handle: handleEl,
      scrollContainer: contentEl,
      backdrop: backdropEl,
      scrim: screenEl,
      mode,
      snapPoints,
      allowed,
      initial,
      animation,
      spring,
      focusTrap,
      closeOnEscape,
      closeOnBack,
      lockBodyScroll,
      rubberBand,
      backdropRange,
    });
    const sync = () => {
      if (!engine) return;
      viewState = { ...engine.state } as EngineState & { activeId: TId };
      onchange?.(viewState);
    };
    sync();
    engine.on("snap", payload => {
      sync();
      onsnap?.(payload.id as TId);
    });
    engine.on("open", payload => onopen?.(payload.id as TId));
    engine.on("close", () => onclose?.());
    engine.on("dragstart", sync);
    engine.on("dragend", sync);
  });

  onDestroy(() => {
    engine?.destroy();
    engine = null;
  });

  export const snapTo = (id: TId) =>
    engine?.snapTo(id) ?? Promise.resolve();
  export const open = (id?: TId) =>
    engine?.open(id) ?? Promise.resolve();
  export const close = () => engine?.close() ?? Promise.resolve();
  export const setAllowed = (ids: TId[], snap?: TId) =>
    engine?.setAllowed(ids as unknown as string[], snap);
  export const setSnapPoints = (
    points: EngineOptions["snapPoints"],
    nextAllowed?: string[],
  ) => engine?.setSnapPoints(points, nextAllowed);
  export const setScrim = (opts: ScrimUpdate) => engine?.setScrim(opts);
  export const setScrimOverlay = (opts: ScrimOverlayOptions): (() => void) =>
    engine?.setScrimOverlay(opts) ?? (() => {});
  export const getState = (): EngineState & { activeId: TId } =>
    (engine?.state ?? viewState) as EngineState & { activeId: TId };
  export const getEngine = (): BottomSheetEngine | null => engine;

  let allowedIds = $derived(
    allowed && allowed.length > 0
      ? allowed
      : snapPoints.map(s => s.id),
  );
  let activeIdx = $derived(allowedIds.indexOf(viewState.activeId));
  let isVerticalAxis = $derived(mode === "bottom" || mode === "top");
</script>

<div class="bs-root">
  {#if backdrop}
    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div
      class="bs-backdrop"
      bind:this={backdropEl}
      aria-hidden="true"
      onclick={closeOnBackdrop ? () => engine?.close() : undefined}
    ></div>
  {/if}
  <div class="bs-screen" bind:this={screenEl}>
    {#if screen}{@render screen()}{/if}
  </div>
  <!-- svelte-ignore a11y_no_noninteractive_element_to_interactive_role -->
  <section
    class="bs-sheet"
    bind:this={sheetEl}
    data-mode={mode}
    data-active={viewState.activeId}
    role="dialog"
    aria-modal={focusTrap ? "true" : undefined}
    aria-label={ariaLabel}
  >
    {#if leftButton}
      <div class="bs-button-slot" data-side="left">
        {@render leftButton()}
      </div>
    {/if}
    {#if rightButton}
      <div class="bs-button-slot" data-side="right">
        {@render rightButton()}
      </div>
    {/if}
    <div
      class="bs-handle"
      bind:this={handleEl}
      role="slider"
      tabindex="0"
      aria-label="Resize sheet"
      aria-orientation={isVerticalAxis ? "vertical" : "horizontal"}
      aria-valuemin={0}
      aria-valuemax={Math.max(0, allowedIds.length - 1)}
      aria-valuenow={Math.max(0, activeIdx)}
      aria-valuetext={viewState.activeId}
    >
      {#if header}{@render header(viewState)}{/if}
    </div>
    <!-- svelte-ignore a11y_no_noninteractive_tabindex -->
    <div class="bs-content" bind:this={contentEl} tabindex="0" role="region" aria-label="Sheet content">
      {#if children}{@render children()}{/if}
    </div>
    <span class="bs-sr-only" role="status" aria-live="polite">
      {viewState.activeId}
    </span>
  </section>
</div>
