// demo/apps/lit-demo.ts
import { LitElement, html } from "lit";
import { repeat } from "lit/directives/repeat.js";
import "@surdeddd/bottom-sheet/element";
import type { BottomSheetElement } from "@surdeddd/bottom-sheet/element";
import type { EngineState } from "@surdeddd/bottom-sheet";
import {
  allowedFromSnaps,
  buildShell,
  demoRows,
  snapPoints,
  type DemoController,
  type DemoSettings,
} from "./shared";

class LitDemoSheet extends LitElement {
  static override properties = {
    settings: { attribute: false },
  };

  declare settings: DemoSettings;

  protected override createRenderRoot(): HTMLElement {
    return this;
  }

  override render(): unknown {
    const mode = this.settings.mode === "overlay" ? "bottom" : this.settings.mode;
    return html`
      <bottom-sheet
        mode=${mode}
        snap-points=${JSON.stringify(snapPoints(mode))}
        initial=${this.settings.initial}
        allowed=${allowedFromSnaps(this.settings.mode).join(",")}
        animation="spring"
        focus-trap=${String(this.settings.focusTrap)}
        close-on-escape=${String(this.settings.closeOnEscape)}
        lock-body-scroll="false"
        stylesheet="/style.css"
      >
        <div slot="header" class="sheet-header">
          <h2>Active routes</h2>
          <span class="hint">LIT · LITELEMENT</span>
        </div>
        <div class="sheet-list">
          ${repeat(
            demoRows,
            ([title]) => title,
            ([title, sub]) => html`
              <div class="sheet-item">
                <div class="sheet-item-dot"></div>
                <div class="sheet-item-text">
                  <strong>${title}</strong><span>${sub}</span>
                </div>
              </div>
            `,
          )}
        </div>
      </bottom-sheet>
    `;
  }

  getSheet(): BottomSheetElement | null {
    return this.querySelector("bottom-sheet") as BottomSheetElement | null;
  }
}

if (!customElements.get("lit-demo-sheet")) {
  customElements.define("lit-demo-sheet", LitDemoSheet);
}

export const mountLitDemo = (
  host: HTMLElement,
  settings: DemoSettings,
): DemoController => {
  const shell = buildShell(host, "Issue 05 · Lit");

  const litRoot = document.createElement("lit-demo-sheet") as LitDemoSheet;
  litRoot.settings = settings;
  shell.append(litRoot);

  let updateCb: ((s: EngineState) => void) | null = null;
  let velocityCb: ((v: number) => void) | null = null;
  let lastSize = 0;
  let lastTs = performance.now();
  let interval: number | null = null;

  requestAnimationFrame(() => {
    interval = window.setInterval(() => {
      const sheet = litRoot.getSheet();
      const state = sheet?.sheetState;
      if (!state) return;
      updateCb?.(state);
      const now = performance.now();
      const dt = now - lastTs;
      if (dt > 0) velocityCb?.((state.size - lastSize) / dt);
      lastSize = state.size;
      lastTs = now;
    }, 33);
  });

  return {
    destroy: () => {
      if (interval) clearInterval(interval);
      litRoot.remove();
    },
    snapTo: (id: string) => {
      void litRoot.getSheet()?.snapTo(id);
    },
    onUpdate: (fn: (s: EngineState) => void) => {
      updateCb = fn;
    },
    onVelocity: (fn: (v: number) => void) => {
      velocityCb = fn;
    },
    getEngine: () => litRoot.getSheet()?.getEngine() ?? null,
  };
};

// demo/apps/solid-demo.tsx
/** @jsxImportSource solid-js */
import { render } from "solid-js/web";
import { onMount, onCleanup, For } from "solid-js";
import { BottomSheetEngine } from "../../src/core/BottomSheetEngine";
import {
  allowedFromSnaps,
  buildShell,
  demoRows,
  snapPoints,
  type DemoController,
  type DemoSettings,
} from "./shared";

const SolidSheet = (props: {
  settings: DemoSettings;
  onReady: (engine: BottomSheetEngine) => void;
  onTeardown: () => void;
}) => {
  let sheetEl!: HTMLDivElement;
  let handleEl!: HTMLDivElement;
  let contentEl!: HTMLDivElement;
  let backdropEl!: HTMLDivElement;
  let engine: BottomSheetEngine | null = null;
  let detachBackdrop: (() => void) | null = null;

  onMount(() => {
    const dataMode =
      props.settings.mode === "overlay" ? "bottom" : props.settings.mode;
    engine = new BottomSheetEngine({
      element: sheetEl,
      handle: handleEl,
      scrollContainer: contentEl,
      backdrop: backdropEl,
      mode: dataMode as "bottom" | "top" | "left" | "right",
      snapPoints: snapPoints(props.settings.mode),
      allowed: allowedFromSnaps(props.settings.mode),
      initial: props.settings.initial,
      animation: "spring",
      spring: {
        stiffness: props.settings.stiffness,
        damping: props.settings.damping,
      },
      focusTrap: props.settings.focusTrap,
      closeOnEscape: props.settings.closeOnEscape,
      rubberBand: props.settings.rubberBand,
      backdropRange: [0.4, 1],
      lockBodyScroll: false,
    });

    const onBackdropClick = () => void engine!.close();
    backdropEl.addEventListener("click", onBackdropClick);
    detachBackdrop = () =>
      backdropEl.removeEventListener("click", onBackdropClick);

    props.onReady(engine);
  });

  onCleanup(() => {
    detachBackdrop?.();
    engine?.destroy();
    engine = null;
    props.onTeardown();
  });

  const dataMode =
    props.settings.mode === "overlay" ? "bottom" : props.settings.mode;

  return (
    <div class="bs-root">
      <div class="bs-backdrop" ref={backdropEl!} />
      <section
        class="bs-sheet"
        data-mode={dataMode}
        role="dialog"
        ref={sheetEl!}
      >
        <div
          class="bs-handle"
          role="slider"
          tabIndex={0}
          aria-label="Resize sheet"
          ref={handleEl!}
        >
          <div class="sheet-header">
            <h2>Active routes</h2>
            <span class="hint">SOLID · SIGNALS</span>
          </div>
        </div>
        <div class="bs-content" ref={contentEl!} tabIndex={0} role="region" aria-label="Sheet content">
          <div class="sheet-list">
            <For each={demoRows}>
              {([title, sub]) => (
                <div class="sheet-item">
                  <div class="sheet-item-dot" />
                  <div class="sheet-item-text">
                    <strong>{title}</strong>
                    <span>{sub}</span>
                  </div>
                </div>
              )}
            </For>
          </div>
        </div>
      </section>
    </div>
  );
};

export const mountSolidDemo = (
  host: HTMLElement,
  settings: DemoSettings,
): DemoController => {
  const shell = buildShell(host, "Issue 04 · Solid");
  const mountPoint = document.createElement("div");
  shell.append(mountPoint);

  let engineRef: BottomSheetEngine | null = null;

  const dispose = render(
    () => (
      <SolidSheet
        settings={settings}
        onReady={engine => {
          engineRef = engine;
        }}
        onTeardown={() => {
          engineRef = null;
        }}
      />
    ),
    mountPoint,
  );

  let updateCb: ((s: any) => void) | null = null;
  let velocityCb: ((v: number) => void) | null = null;
  let lastSize = 0;
  let lastTs = performance.now();

  const interval = window.setInterval(() => {
    if (!engineRef) return;
    const state = engineRef.state;
    updateCb?.(state);
    const now = performance.now();
    const dt = now - lastTs;
    if (dt > 0) velocityCb?.((state.size - lastSize) / dt);
    lastSize = state.size;
    lastTs = now;
  }, 33);

  return {
    destroy: () => {
      clearInterval(interval);
      dispose();
      mountPoint.remove();
    },
    snapTo: (id: string) => {
      void engineRef?.snapTo(id);
    },
    onUpdate: fn => {
      updateCb = fn;
    },
    onVelocity: fn => {
      velocityCb = fn;
    },
    getEngine: () => engineRef ?? null,
  };
};
