// src/react/BottomSheet.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from "react";
import { createPortal } from "react-dom";
import { useBottomSheet } from "./useBottomSheet";
import type { BottomSheetEngine } from "../core/BottomSheetEngine";
import type {
  CloseReason,
  EngineOptions,
  EngineState,
  SheetEventMap,
} from "../core/types";
import type { TeleportTarget } from "../core/features/teleport";
import type { AnchorOptions } from "../core/features/sheet-anchors";
import type {
  ScrimStageDef,
  ScrimStagesOptions,
} from "../core/features/scrim-stages";

const useHasMounted = () => {
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  return mounted;
};

type EngineOptionsForProps = Omit<
  EngineOptions,
  "element" | "handle" | "scrollContainer" | "backdrop" | "scrim"
>;

export type HeaderProp = ReactNode | ((state: EngineState) => ReactNode);

export type BottomSheetAnchorProp = Omit<AnchorOptions, "element"> & {
  node: ReactNode;
};

export type BottomSheetScrimStageProp = Omit<ScrimStageDef, "element"> & {
  node: ReactNode;
};

export type BottomSheetScrimStagesProp = Omit<ScrimStagesOptions, "stages"> & {
  stages: BottomSheetScrimStageProp[];
};

export type BottomSheetProps = EngineOptionsForProps & {
  backdrop?: boolean;
  closeOnBackdrop?: boolean;
  className?: string;
  style?: CSSProperties;
  header?: HeaderProp;
  footer?: HeaderProp;
  children?: ReactNode;
  leftButton?: ReactNode;
  rightButton?: ReactNode;
  screen?: ReactNode;
  anchors?: BottomSheetAnchorProp[];
  scrimStages?: BottomSheetScrimStagesProp;
  teleportTo?: TeleportTarget;
  backdropColor?: string;
  backdropOpacity?: number;
  onChange?: (state: EngineState) => void;
  onSnap?: (id: string) => void;
  onBeforeSnap?: (payload: SheetEventMap["before-snap"]) => void;
  onBeforeClose?: (payload: SheetEventMap["before-close"]) => void;
  onOpen?: (id: string) => void;
  onClose?: () => void;
  onOpened?: (id: string) => void;
  onClosed?: () => void;
  onDragStart?: (payload: SheetEventMap["dragstart"]) => void;
  onDragEnd?: (payload: SheetEventMap["dragend"]) => void;
  onDrag?: (payload: SheetEventMap["drag"]) => void;
  onProgress?: (payload: SheetEventMap["progress"]) => void;
  ariaLabel?: string;
  ariaLabelledBy?: string;
  noSSR?: boolean;
};

export type BottomSheetHandle<TId extends string = string> = {
  snapTo: (id: TId) => Promise<void>;
  open: (id?: TId) => Promise<void>;
  close: (reason?: CloseReason) => Promise<void>;
  expand: () => Promise<void>;
  collapse: () => Promise<void>;
  isTop: () => boolean;
  depth: () => number;
  setAllowed: (ids: TId[], snap?: TId) => void;
  setSnapPoints: (
    points: import("../core/types").EngineOptions["snapPoints"],
    allowed?: string[],
  ) => void;
  setScrim: (opts: import("../core/types").ScrimUpdate) => void;
  setScrimOverlay: (
    opts: import("../core/types").ScrimOverlayOptions,
  ) => () => void;
  addAnchor: (opts: AnchorOptions) => () => void;
  setScrimStages: (opts: ScrimStagesOptions | null) => () => void;
  recompute: () => void;
  state: EngineState & { activeId: TId };
  getEngine: () => BottomSheetEngine | null;
};

export const BottomSheet = forwardRef<BottomSheetHandle, BottomSheetProps>(
  function BottomSheet(props, ref) {
    const {
      backdrop = true,
      closeOnBackdrop = true,
      className = "",
      style,
      header,
      footer,
      children,
      leftButton,
      rightButton,
      screen,
      anchors,
      scrimStages,
      onChange,
      onBeforeClose,
      onOpen,
      onClose,
      onOpened,
      onClosed,
      onDragStart,
      onDragEnd,
      onDrag,
      onProgress,
      ariaLabel = "Bottom sheet",
      ariaLabelledBy,
      noSSR = false,
      ...engineOpts
    } = props;
    const mounted = useHasMounted();

    const {
      sheetRef,
      handleRef,
      contentRef,
      backdropRef,
      screenRef,
      state,
      snapTo,
      open,
      close,
      expand,
      collapse,
      isTop,
      depth,
      setAllowed,
      getEngine,
    } = useBottomSheet({
      ...engineOpts,
      onBeforeClose,
      onOpen,
      onClose,
      onOpened,
      onClosed,
      onDragStart,
      onDragEnd,
      onDrag,
      onProgress,
    });

    const ariaModal = engineOpts.focusTrap === true;

    const lastAnnouncedRef = useRef<string>("");
    const [announce, setAnnounce] = useState("");
    useEffect(() => {
      if (state.activeId !== lastAnnouncedRef.current) {
        lastAnnouncedRef.current = state.activeId;
        setAnnounce(state.activeId);
      }
    }, [state.activeId]);

    useImperativeHandle(
      ref,
      () => ({
        snapTo,
        open,
        close,
        expand,
        collapse,
        isTop,
        depth,
        setAllowed,
        setSnapPoints: (points, allowed) =>
          getEngine()?.setSnapPoints(points, allowed),
        setScrim: opts => getEngine()?.setScrim(opts),
        setScrimOverlay: opts => getEngine()?.setScrimOverlay(opts) ?? (() => {}),
        addAnchor: opts => getEngine()?.addAnchor(opts) ?? (() => {}),
        setScrimStages: opts => getEngine()?.setScrimStages(opts) ?? (() => {}),
        recompute: () => getEngine()?.recompute(),
        getEngine,
        get state() {
          return getEngine()?.state ?? state;
        },
      }),
      [
        snapTo,
        open,
        close,
        expand,
        collapse,
        isTop,
        depth,
        setAllowed,
        getEngine,
        state,
      ],
    );

    useEffect(() => {
      onChange?.(state);
    }, [state, onChange]);

    const [anchorHosts, setAnchorHosts] = useState<HTMLElement[]>([]);
    const anchorsKey = anchors
      ? JSON.stringify(
          anchors.map(a => [
            a.position,
            a.inset,
            Array.isArray(a.showOn) ? a.showOn : a.showOn ? "fn" : null,
            a.fadeRange,
            a.interactive,
            typeof a.animation === "string"
              ? a.animation
              : a.animation
                ? "custom"
                : null,
          ]),
        )
      : "";
    useEffect(() => {
      const engine = getEngine();
      if (!engine || !anchors || anchors.length === 0) return;
      const hosts: HTMLElement[] = [];
      const detachers = anchors.map(a => {
        const host = document.createElement("div");
        hosts.push(host);
        const { node: _node, ...rest } = a;
        return engine.addAnchor({ ...rest, element: host });
      });
      setAnchorHosts(hosts);
      return () => {
        detachers.forEach(d => d());
        setAnchorHosts([]);
      };
    }, [getEngine, anchorsKey]);

    const [stageHosts, setStageHosts] = useState<HTMLElement[]>([]);
    const stagesKey = scrimStages
      ? JSON.stringify(
          scrimStages.stages.map(s => [
            s.for,
            s.forRange,
            s.position,
            s.inset,
            s.interactive,
            typeof s.animation === "string"
              ? s.animation
              : s.animation
                ? "custom"
                : null,
          ]),
        )
      : "";
    useEffect(() => {
      const engine = getEngine();
      if (!engine || !scrimStages || scrimStages.stages.length === 0) return;
      const hosts: HTMLElement[] = [];
      const defs = scrimStages.stages.map(s => {
        const host = document.createElement("div");
        hosts.push(host);
        const { node: _node, ...rest } = s;
        return { ...rest, element: host };
      });
      const detach = engine.setScrimStages({ ...scrimStages, stages: defs });
      setStageHosts(hosts);
      return () => {
        detach();
        setStageHosts([]);
      };
    }, [getEngine, stagesKey]);

    if (noSSR && !mounted) return null;

    return (
      <div className="bs-root">
        {backdrop && (
          <div
            ref={backdropRef as React.RefObject<HTMLDivElement>}
            className="bs-backdrop"
            onClick={
              closeOnBackdrop
                ? () => {
                    if (getEngine()?.canDismiss()) void close("backdrop");
                  }
                : undefined
            }
          />
        )}
        <div
          ref={screenRef as React.RefObject<HTMLDivElement>}
          className="bs-screen"
        >
          {screen}
        </div>
        <section
          ref={sheetRef as React.RefObject<HTMLElement>}
          className={`bs-sheet ${className}`.trim()}
          style={style}
          data-mode={engineOpts.mode ?? "bottom"}
          data-active={state.activeId}
          role={ariaModal ? "dialog" : "region"}
          aria-modal={ariaModal ? "true" : undefined}
          aria-label={ariaLabelledBy ? undefined : ariaLabel}
          aria-labelledby={ariaLabelledBy}
        >
          <div
            ref={handleRef as React.RefObject<HTMLDivElement>}
            className="bs-handle"
            role="slider"
            tabIndex={0}
            aria-label="Resize sheet"
          />
          {header != null && header !== false && (
            <div className="bs-header">
              {typeof header === "function" ? header(state) : header}
            </div>
          )}
          <div
            ref={contentRef as React.RefObject<HTMLDivElement>}
            className="bs-content"
            tabIndex={0}
            role="region"
            aria-label="Sheet content"
          >
            {children}
          </div>
          {footer != null && footer !== false && (
            <div className="bs-footer">
              {typeof footer === "function" ? footer(state) : footer}
            </div>
          )}
          <span className="bs-sr-only" role="status" aria-live="polite">
            {announce}
          </span>
        </section>
        {leftButton && (
          <div
            className="bs-button-slot"
            data-side="left"
            data-mode={engineOpts.mode ?? "bottom"}
          >
            {leftButton}
          </div>
        )}
        {rightButton && (
          <div
            className="bs-button-slot"
            data-side="right"
            data-mode={engineOpts.mode ?? "bottom"}
          >
            {rightButton}
          </div>
        )}
        {anchorHosts.map((host, i) =>
          anchors?.[i] ? createPortal(anchors[i]!.node, host) : null,
        )}
        {stageHosts.map((host, i) =>
          scrimStages?.stages[i]
            ? createPortal(scrimStages.stages[i]!.node, host)
            : null,
        )}
      </div>
    );
  },
);

// src/vue/BottomSheet.vue
<script setup lang="ts" generic="TId extends string = string">
import {
  computed,
  onBeforeUnmount,
  onMounted,
  readonly,
  ref,
  shallowRef,
  watch,
  type TeleportProps,
} from "vue";
import { useBottomSheet, type UseBottomSheetVueOptions } from "./useBottomSheet";
import type { CloseReason, EngineState } from "../core/types";
import type { AnchorOptions } from "../core/features/sheet-anchors";
import type { ScrimStagesOptions } from "../core/features/scrim-stages";

type VueAnchor = Omit<AnchorOptions, "element"> & { id: string };

type Props = UseBottomSheetVueOptions<TId> & {
  backdrop?: boolean;
  closeOnBackdrop?: boolean;
  ariaLabel?: string;
  open?: boolean;
  snap?: TId;
  teleport?: boolean;
  teleportTo?: TeleportProps["to"];
  anchors?: VueAnchor[];
  scrimStages?: ScrimStagesOptions | null;
  backdropColor?: string;
  backdropOpacity?: number;
};

const props = withDefaults(defineProps<Props>(), {
  backdrop: true,
  closeOnBackdrop: true,
  ariaLabel: "Bottom sheet",
  teleport: true,
  teleportTo: "body",
});

const emit = defineEmits<{
  change: [state: EngineState & { activeId: TId }];
  snap: [id: TId];
  open: [id: TId];
  close: [];
  opened: [id: TId];
  closed: [];
  "before-close": [payload: { reason: CloseReason; cancel: () => void }];
  "before-snap": [
    payload: {
      id: TId;
      size: number;
      previousId: string;
      cancel: () => void;
    },
  ];
  "drag-start": [payload: { size: number }];
  "drag-end": [payload: { size: number; velocity: number }];
  "update:open": [open: boolean];
  "update:snap": [id: TId];
}>();

const {
  sheetRef,
  handleRef,
  contentRef,
  backdropRef,
  screenRef,
  state,
  snapTo,
  open,
  close,
  setAllowed,
  setSnapPoints,
  setScrim,
  setScrimOverlay,
  addAnchor,
  setScrimStages,
  recompute,
  setScrimColor,
  setBackdropRange,
  setRadius,
  setMaxHeight,
  expand,
  collapse,
  isTop,
  depth,
  canDismiss,
  on,
  getEngine,
} = useBottomSheet<TId>(props);

watch(
  () => ({ ...state }),
  next => emit("change", next as EngineState & { activeId: TId }),
  { deep: false },
);

on("snap", payload => {
  emit("snap", payload.id as TId);
  emit("update:snap", payload.id as TId);
});
on("open", payload => {
  emit("open", payload.id as TId);
  emit("update:open", true);
});
on("close", () => {
  emit("close");
  emit("update:open", false);
});
on("opened", payload => emit("opened", payload.id as TId));
on("closed", () => emit("closed"));
on("before-close", payload => emit("before-close", payload));
on("before-snap", payload =>
  emit("before-snap", {
    id: payload.id as TId,
    size: payload.size,
    previousId: payload.previousId,
    cancel: payload.cancel,
  }),
);
on("dragstart", payload => emit("drag-start", payload));
on("dragend", payload => emit("drag-end", payload));

watch(
  () => props.open,
  next => {
    if (next === undefined) return;
    const isOpen = state.size > 0;
    if (next && !isOpen) void open();
    else if (!next && isOpen) void close();
  },
);

watch(
  () => props.snap,
  next => {
    if (next === undefined || next === state.activeId) return;
    void snapTo(next);
  },
);

watch(
  () => props.snapPoints,
  next => {
    if (!next) return;
    setSnapPoints(
      next as unknown as Parameters<typeof setSnapPoints>[0],
      props.allowed as unknown as string[] | undefined,
    );
  },
  { deep: true },
);

watch(
  () => props.allowed,
  next => {
    if (!next) return;
    setAllowed(Array.from(next) as Parameters<typeof setAllowed>[0]);
  },
);

watch(
  () => props.backdropColor,
  next => {
    if (next === undefined) return;
    setScrimColor(next);
  },
);

watch(
  () => props.backdropOpacity,
  next => {
    if (next === undefined) return;
    setBackdropRange([0, next]);
  },
);

watch(
  () => props.radius,
  next => {
    if (next === undefined) return;
    setRadius(next);
  },
);

watch(
  () => props.maxHeight,
  next => {
    if (next === undefined) return;
    setMaxHeight(next);
  },
);

watch(
  () => props.persistent,
  next => {
    if (next === undefined) return;
    getEngine()?.setPersistent(next);
  },
);

watch(
  () => props.disableClose,
  next => {
    if (next === undefined) return;
    getEngine()?.setDisableClose(next);
  },
);

watch(
  () => props.disableDrag,
  next => {
    if (next === undefined) return;
    getEngine()?.setDisableDrag(next);
  },
);

const mounted = ref(false);
const anchorHosts = shallowRef<Record<string, HTMLElement>>({});
const anchorDetachers = ref<Array<() => void>>([]);
let stagesDetach: (() => void) | null = null;

const teardownAnchors = (): void => {
  anchorDetachers.value.forEach(d => d());
  anchorDetachers.value = [];
  anchorHosts.value = {};
};

const buildAnchors = (): void => {
  teardownAnchors();
  const engine = getEngine();
  if (!engine || !props.anchors?.length) return;
  const hosts: Record<string, HTMLElement> = {};
  const detachers: Array<() => void> = [];
  for (const a of props.anchors) {
    const host = document.createElement("div");
    hosts[a.id] = host;
    const { id: _id, ...rest } = a;
    detachers.push(engine.addAnchor({ ...rest, element: host }));
  }
  anchorHosts.value = hosts;
  anchorDetachers.value = detachers;
};

const anchorsKey = computed(() =>
  JSON.stringify(
    (props.anchors ?? []).map(a => [
      a.id,
      a.position,
      a.inset,
      Array.isArray(a.showOn) ? a.showOn : a.showOn ? "fn" : null,
      a.fadeRange,
      a.interactive,
      typeof a.animation === "string" ? a.animation : a.animation ? "x" : null,
    ]),
  ),
);

const applyStages = (): void => {
  stagesDetach?.();
  stagesDetach = null;
  const engine = getEngine();
  if (!engine || !props.scrimStages) return;
  stagesDetach = engine.setScrimStages(props.scrimStages);
};

onMounted(() => {
  mounted.value = true;
  buildAnchors();
  applyStages();
  watch(anchorsKey, buildAnchors);
  watch(() => props.scrimStages, applyStages, { deep: true });
  if (props.open && state.size === 0) void open();
});

onBeforeUnmount(() => {
  teardownAnchors();
  stagesDetach?.();
  stagesDetach = null;
});

const isVerticalAxis = computed(() => {
  const mode = props.mode ?? "bottom";
  return mode === "bottom" || mode === "top";
});
const ariaModal = computed(() => props.focusTrap === true);

defineExpose({
  snapTo,
  open,
  close,
  setAllowed,
  setSnapPoints,
  setScrim,
  setScrimOverlay,
  addAnchor,
  setScrimStages,
  recompute,
  setScrimColor,
  setBackdropRange,
  setRadius,
  setMaxHeight,
  expand,
  collapse,
  isTop,
  depth,
  canDismiss,
  on,
  getEngine,
  state: readonly(state),
});
</script>

<template>
  <Teleport :to="teleportTo" :disabled="!teleport || !mounted">
    <div class="bs-root">
      <div
        v-if="backdrop"
        ref="backdropRef"
        class="bs-backdrop"
        aria-hidden="true"
        @click="closeOnBackdrop && canDismiss() ? close('backdrop') : undefined"
      />
      <div ref="screenRef" class="bs-screen">
        <slot name="screen" />
      </div>
      <section
        ref="sheetRef"
        :class="['bs-sheet']"
        :data-mode="props.mode ?? 'bottom'"
        :data-active="state.activeId"
        :role="ariaModal ? 'dialog' : 'region'"
        :aria-modal="ariaModal ? 'true' : undefined"
        :aria-label="ariaLabel"
      >
        <div
          ref="handleRef"
          class="bs-handle"
          role="slider"
          tabindex="0"
          :aria-orientation="isVerticalAxis ? 'vertical' : 'horizontal'"
          aria-label="Resize sheet"
        />
        <div v-if="$slots.header" class="bs-header">
          <slot name="header" :state="state" />
        </div>
        <div
          ref="contentRef"
          class="bs-content"
          tabindex="0"
          role="region"
          aria-label="Sheet content"
        >
          <slot />
        </div>
        <div v-if="$slots.footer" class="bs-footer">
          <slot name="footer" :state="state" />
        </div>
        <span class="bs-sr-only" role="status" aria-live="polite">
          {{ state.activeId }}
        </span>
      </section>
      <div
        v-if="$slots['button-left']"
        class="bs-button-slot"
        data-side="left"
        :data-mode="props.mode ?? 'bottom'"
      >
        <slot name="button-left" />
      </div>
      <div
        v-if="$slots['button-right']"
        class="bs-button-slot"
        data-side="right"
        :data-mode="props.mode ?? 'bottom'"
      >
        <slot name="button-right" />
      </div>
    </div>
    <Teleport
      v-for="a in props.anchors ?? []"
      :key="a.id"
      :to="anchorHosts[a.id]"
      :disabled="!anchorHosts[a.id]"
    >
      <slot :name="`anchor-${a.id}`" :state="state" />
    </Teleport>
  </Teleport>
</template>
